@startuml C4_Elements
!include <C4/C4_Container>
!include <C4/C4_Component>
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
'!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites
'!include SPRITESURL/flask.puml
!include DEVICONS2/flask_original.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/sqllite.puml



AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="white")
AddElementTag("package", $shape=dBoxShape(), $bgColor="lightSkyBlue", $fontColor="white")

SHOW_PERSON_OUTLINE()
Person(operator, "Пользователь", "Основной пользователь системы")

System_Boundary(main, "Основная система") {
    Container(web_client, "Web-интерфейс", $techn="Flask", $sprite="flask_original")

    Container_Boundary(api_server, "Backend") {
        Container(fast_api_server, "Web API", $techn="FastAPI, SQLAlchemy")
        ContainerDb(db, "База данных", $techn="PostgeSQL", $sprite="postgresql")
    }
    Container_Boundary(map_api_container , "API карт") {
        Container(map_api, "API карт", $techn="FastAPI")
        ContainerDb(db_sqllite, "MBTiles", $techn="SQLLite", $sprite="sqllite")
    }
    Container(fire_detector, "Детектор пожаров", $techn="FastAPI, pytorch")
}


Rel_D(web_client, fast_api_server, "Использование", $techn="REST API")
Rel_D(fast_api_server, db, "Чтение/запись", $techn="SQLAlchemy")
Rel_R(fire_detector, fast_api_server, "Чтение/запись данных", $techn="REST API")
Rel_U(operator, web_client, "Использование", $techn="REST API")
Rel_L(map_api, db_sqllite, "Запрос tiles", $techn="REST API")
BiRel_D(map_api, fast_api_server, "Чтение/запись информации о tiles", $techn="REST API")
BiRel_R(web_client, map_api, "Запрос tiles", $techn="REST API")

@enduml